url: "http://nantes.afup.org"

title: "AFUP Nantes"
description: >-
  Antenne AFUP sur Nantes
twitter_username: AFUP_Nantes
meetup_url: "https://www.meetup.com/fr-FR/afup-nantes-php/"

permalink: /posts/:title

ga_ua: "G-V8VWN2N1V8"
home_featured_articles_count: 1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Makefile
   - docker-compose.yml
   - docker-compose.override.yml-dist
   - docker-compose.override.yml
   - Gemfile
   - Gemfile.lock

feed:
  path: feed

